### ISSUE TITLE
unable to compile indi driver

### ISSUE THREAD

**Issue by Trigger-broom-289** [dokeeffe/cloud-rain-monitor#1]
Hello,

I have the latest indi lib installed.

ii  libindi-data                1.4.1+r3089~201705200923~ubuntu16.04.1        all          Instrument-Neutral Device Interface library -- shared data
ii  libindi-dev                 1.4.1+r3089~201705200923~ubuntu16.04.1        armhf        Instrument-Neutral Device Interface library -- development files
ii  libindi1:armhf              1.4.1+r3089~201705200923~ubuntu16.04.1        armhf        Instrument-Neutral Device Interface library -- shared library

An trying to compile your driver gives me the following error:
`root@odroid:/home/cloud-rain-monitor/indi-driver# ./build.sh 
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libindi'
--   Found libindi, version 1.4.1
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find INDI (missing: INDI_LIBRARIES) (found version "1.4.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindINDI.cmake:66 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/cloud-rain-monitor/indi-driver/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'install'.  Stop.
root@odroid:/home/cloud-rain-monitor/indi-driver#`

Stephane

**Comment by Trigger-broom-289** [comment]
just a quick note to mention that I had no issues building up the indi driver for the Aldi-roof, as in 10 min before doing this one.

**Comment by dokeeffe** [comment]
Thanks, I'll have a look. I think I know what it is. Changes from INDI 1.4, I fixed locally but must have forgot to push to github.

**Comment by Trigger-broom-289** [comment]
ok thanks for looking into this, appreciated.

**Comment by dokeeffe** [comment]
No problem!

**Comment by dokeeffe** [comment]
Just pushed my changes there now. Should build now.

**Comment by Trigger-broom-289** [comment]
thanks for fixing this, I can confirm it compiles fine now.


root@odroid:/home/cloud-rain-monitor/indi-driver# ./build.sh 
mkdir: cannot create directory 'build': File exists
-- The CXX compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found INDI: /usr/lib/arm-linux-gnueabihf/libindidriver.so;/usr/lib/arm-linux-gnueabihf/libindiAlignmentDriver.so (found version "1.4.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cloud-rain-monitor/indi-driver/build
Scanning dependencies of target indi_cloud_rain_monitor
[ 33%] Building CXX object CMakeFiles/indi_cloud_rain_monitor.dir/cloudrainmonitor.o
[ 66%] Building CXX object CMakeFiles/indi_cloud_rain_monitor.dir/gason.o
[100%] Linking CXX executable indi_cloud_rain_monitor
[100%] Built target indi_cloud_rain_monitor
Install the project...
-- Install configuration: ""
-- Installing: /usr/bin/indi_cloud_rain_monitor
-- Installing: /usr/share/indi/indi_cloud_rain_monitor.xml
root@odroid:/home/cloud-rain-monitor/indi-driver#

**Comment by dokeeffe** [comment]
Oh yes.... there is a nasty hard coded IP address in cloudrainmonitor.cpp line 170.... Its the IP of the raspberry pi weather station.... You will have to change this! If you could add the option to the driver and send a PR it would be even better :-)

**Comment by dokeeffe** [comment]
Also if you need any photos / details of the RPI arduino setup let me know...

**Comment by Trigger-broom-289** [comment]
I guess I need to put the IP of my Odroid there?

**Comment by dokeeffe** [comment]
Yes, actually its ok. You can change it in the driver in the options tab. Sorry for the confusion!! I was confused with something else. So you are using an Odroid? It should work fine as long as the Odroid provides the same HTTP API. So for example, if you go to http://<odroid-address>/weather it should respond with the json response that the driver is expecting. If you run the same weatherMicroService.py on the odroid then it should be fine. The weatherMicroService.py is in device/rpi/web
