### ISSUE TITLE
Always cloudy in chart?

### ISSUE THREAD

**Issue by Trigger-broom-289** [dokeeffe/cloud-rain-monitor#4]
I'm testing the charts again and there is something odd about cloud coverage.

At the present time, it is cloud less, not a single one in sight.
the report shows:
{"rain": false, "readingTimestamp": "2017-08-22 09:13:38", "outsideTemp": 24.77, "skyTemp": 14.79}

the code is:
    def _calculate_cloud_cover(self, sky, ambient):
        '''
        Needs work. +22ambient and -2.5sky and sky was 90% clear
        :param sky:
        :param ambient:
        :return:
        '''
        cc = ((sky+20)*7)-ambient
        if cc > 100:
            cc = 100
        if cc < 10:
            cc = 0
        return cc

So from the above report:
 cc= ((14.79+20)*7)-24.77
 cc= 218.76
 cc > 100 so it's cloudy but it's not cloudy out there right now, blue sky.

**Comment by Trigger-broom-289** [comment]
Looking at the following two links that might help with the cloud coverage formula

https://indiduino.wordpress.com/2013/02/02/meteostation/
https://sourceforge.net/p/indi/code/HEAD/tree/trunk/3rdparty/indi-duino/devices/Firmwares/indiduinoMETEO/indiduinoMETEO.ino

**Comment by dokeeffe** [comment]
Yes if you can come up with a better function then please do. My one is not good at day time when the ambient temp is high. However I see your sky temp above is "skyTemp": 14.79}. Are you sure its clear and the sensor is pointing at the sky? Generally I get negative temperatures if the sky is clear. Might there be a tree or building in the way?

**Comment by dokeeffe** [comment]
That second link looks really interesting thanks 'From AAG Cloudwatcher formula' 
Could you try that formula/function and see if its better for your sky? I'll also try in the next few days or so

**Comment by Trigger-broom-289** [comment]
I will see what I can come up for the formula, I remember when I had that indi meteostation that the cloud cover was very accurate. I was pleasantly surprised by it.

I will review my sensor position.

**Comment by Trigger-broom-289** [comment]
I believe the IR sensor is also picking up ambient temperature, heat reflecting from my box.
Oh the clouds are rolling in... what a surprise... typical... lol

**Comment by dokeeffe** [comment]
Yes my one does this too but not as much I think

**Comment by Trigger-broom-289** [comment]
I'm trying to get my head around this cloud detection and I see different formulas in your code.

**cloudrainmonitor.cpp**
//Function based on data collected, guesswork and linear regression using wolframalpha https://www.wolframalpha.com/input/?i=linear+fit+{0,+100},{-1,+90},{-2,+80},{-3,+50},{-4,+25},{-5,+10},{-6,0}&lk=3
        double result = (18 * skyTemp) + 100;
        if(result > 100) {
            result = 100;

while in **charts.py**
cc = ((sky+20)*7)-ambient

**Comment by dokeeffe** [comment]
Yea, I'm still experimenting with different formulas, Both should be the same, hopefully the AAG formula can replace both

**Comment by Trigger-broom-289** [comment]
Found an interesting link about the sensor.
http://www.kwos.org/clouds_detector.htm

**This Clouds Detector Sensor uses a thermopile sensor (MLX90614 family)directed to zenith. This sensor integrates radiation over the 120° of the sky. Clear view to the sky is important because any terrestrial objects can cause parasite IR radiation.
In fact two zones are measured by the thermopile sensor each with approximately 90° FOV.**


That means, I will probably have to relocate this sensor, and also the rain sensor.....

**Comment by dokeeffe** [comment]
Interesting, yes my one is on the roof and has a clear view of the sky

**Comment by Trigger-broom-289** [comment]
As an experiment, I have moved my box (it's ok, it's not live). The sensor is now further away from nearby objects and the temperature measured has dropped.
So, I will have to totally relocate it. That's a job for next holidays I'm afraid :(


I'll be curious to see what new formula you can come up with, I will also look on my side.

**Comment by Trigger-broom-289** [comment]
**EXPERIMENTAL CODE:**

import math
```
    def _calculate_cloud_cover(self, sky, ambient):
        '''
        Needs work. +22ambient and -2.5sky and sky was 90% clear
        :param sky:
        :param ambient:
        :return:
        '''
        #cc = ((sky+20)*7)-ambient
        Td = (33/100)*(ambient-0/10)+(4/100)*math.pow((math.exp(100/1000*ambient)),(100/100))
        cc = sky-Td
        if cc > 10:
            cc = 100
        if cc < 1:
            cc = 0
        return cc
```


using the formula from the AAG code.
I am now getting a better looking cloud chart, not just a 100% cloud, but something that "might" look like cloud passing above.

to be continued...

**Comment by dokeeffe** [comment]
Awesome!!! I'm going to try this right now on my one.

**Comment by Trigger-broom-289** [comment]
We will still have to play with the following:

```
 if cc > 10:
            cc = 100
        if cc < 1:
            cc = 0
```

I picked 10 as random, ok it works at the moment but it might not be the right value.
Right now, I have almost 100% clear sky (visual check). Where are the clouds when you need them !!!

**Comment by Trigger-broom-289** [comment]
trying slightly different formula

```
        #cc = ((sky+20)*7)-ambient
        Td = 0.33*(ambient/10)+0.04*math.pow((math.exp(100/(1000*ambient))),1)
        cc = sky-Td
        if cc > 10:
            cc = 100
        if cc < 1:
            cc = 0
        return cc
```

**Comment by Trigger-broom-289** [comment]
http://www.aagware.eu/aag/cloudwatcher/WebHelp/scr/Operational%20Aspects/23-TemperatureFactor-.htm

```
        :return:
        '''
        k1 = 20
        k2 = 50
        k3 = 25
        k4 = 80
        k5 = 100
        #cc = ((sky+20)*7)-ambient
        Td = (k1*100)*(ambient-k2/10)+(k3/100)*math.pow((math.exp(k4/(1000*ambient))),(k5/100))
        cc = sky-Td
        if cc > 1:
            cc = 100
        if cc < -8:
            cc = 0
        return cc
```


the cc values for < > are the ones we need to work on.

**Comment by dokeeffe** [comment]
Yes its tricky. I tried your first formula last night in the graph. I left the formula in the INDI driver as is.
The sky was clear for about 2hrs and I was running a schedule in EKOS. The weather station plot also said it was clear which was great.... Then it did cloud over ( I was watching an all sky camera) and the indi driver detected the cloud and the scheduler then shutdown (parked and closed) however the station-graph was still showing clear. Only when the clouds got much thicker did the graph show cloud cover. So that cc value is the tricky one.
I have a feeling the only way is to collect data form the station and also visual estimates of cloud cover. Then get a function to fit this data.

**Comment by Trigger-broom-289** [comment]
I think the formula is correct, it's used in the indiuno meteostation and I was quite impressed with it.
But they have more than just the formula, and that's where I'm struggling to understand how they use it really.

They use things like this to calculate the "cc":

```
//Clear sky corrected temperature (temp below means 0% clouds)
#define CLOUD_TEMP_CLEAR  -8 
//Totally cover sky corrected temperature (temp above means 100% clouds)
#define CLOUD_TEMP_OVERCAST  0  
//Activation treshold for cloudFlag (%)
#define CLOUD_FLAG_PERCENT  30
```

```
double cloudIndex() {
   double Tcloudy= CLOUD_TEMP_OVERCAST,Tclear=CLOUD_TEMP_CLEAR;
   double Tsky=skyTemp();
   double Index;
   if (Tsky<Tclear) Tsky=Tclear;
   if (Tsky>Tcloudy) Tsky=Tcloudy;
   Index=(Tsky-Tclear)*100/(Tcloudy-Tclear);
   return Index;
}
```

```
    // This masks off the error bit of the high byte, then moves it left 8 bits and adds the low byte.
    tempData = (double)(((data_high & 0x007F) << 8) + data_low);
    tempData = (tempData /50);
    
    Tir = tempData - 273.15;
    Clouds=cloudIndex();
    skyT=skyTemp();
    if (Clouds >CLOUD_FLAG_PERCENT) {
      cloudy=1;
    } else {
      cloudy=0;
    }
```

**Comment by Trigger-broom-289** [comment]
We can close all of this now.
