### ISSUE TITLE
wrong time logged

### ISSUE THREAD

**Issue by Trigger-broom-289** [dokeeffe/cloud-rain-monitor#5]
Noticed that the time stamp isn't being recorded correctly.

root@heidenrod-obs:/home/cloud_rain# date
Tue Aug 22 **21:01:20** CEST 2017

http:
{"readingTimestamp": "2017-08-22 **19:00:26**", "outsideTemp": 16.99, "skyTemp": 4.71, "rain": false}

**Comment by dokeeffe** [comment]
Thats really strange. I have noticed wrong times logged but it was because the pi's time was wrong. After setting up ntpd it fixed it but your time is correct.... very strange. I'll have a look

**Comment by dokeeffe** [comment]
Ah you are CEST. The time logged in the DB is UTC, no offeset is applied on read so you are getting back the raw UTC time

**Comment by Trigger-broom-289** [comment]
We can close all of this now.
