### ISSUE TITLE
Sensor variant and orientation

### ISSUE THREAD

**Issue by kobuki** [dokeeffe/cloud-rain-monitor#6]
I'm thinking of building a cloud sensor for my weather station a and discovered your solution. It's pretty simple and cheap to build, but I'm not sure about the exact type of the sensor. Are you using the 90° FOV version or another one? They're available down to 5°. Is that parameter important? Also, is the sensor orientation important? So is pointing exactly upwards required, or any angle suffices where the sky view is clear WRT the FOV of the sensor?

**Comment by dokeeffe** [comment]
Hi, yes I got the 90deg FOV version. I was thinking that the narrow FOV one may detect a small passing cloud which would shutdown the observatory. 
Regarding the orientation, my one is pointing almost straight upwards. Its a little to the north (maybe 5 or 10deg at a guess) but this is fine. The main thing is that the FOV does not include anything like trees or buildings as they would read a much higher temp than a clear sky.

**Comment by kobuki** [comment]
I see, thanks for the clarification, it's what I thought. It's pretty hard here to avoid trees with 90° FOV. But from your words it might be possible to narrow the field somewhat to exclude the trees...
